### ISSUE TITLE
安卓可以选择拍照或从相册上传

### ISSUE THREAD

**Issue by levy9527** [FEMessage/upload-to-ali#10]
安卓默认只能代码里写死是拍照，还是从相册上传，需要让安卓类似ios一样，可以让用户选择是拍照还是上
传。

则核心js逻辑：
1. 判断是安卓
2. 组件出现弹出层，让用户选择“拍照”、“上传”

弹出层样式同ios，可参考 http://dev.dcloud.net.cn/mui/
![image](https://user-images.githubusercontent.com/9384365/53311646-9f720d80-38ec-11e9-8001-720047bf7e00.png)

**Comment by 2nthony** [comment]
# 此功能可行性不完全报告

## 小米6 - MIUI 10 - ANDROID 8

### 测试代码为
```html
<!-- 1 -->
<input type="file" accept="image/*">
<!-- 2 -->
<input type="file" accept="image/*" capture>
<!-- 3 -->
<input type="file" accept="image/*" capture="camera">
```

### 小米自带浏览器

> 内核v61

第一个控件为系统级提示

- 相机 -> 调取相机拍照
- 文件 -> 选取照片文件

其余二三控件为直接打开相机

如果`ActionSheet`中`选取现有的`没有设置`capture`属性可能会再弹出一个系统级提示

### Chrome

> 内核v62

第一个控件与小米浏览器行为一直,提供两项可选

二三控件也直接打开相机

总体与小米浏览器行为相同

### Quark 夸克

> 内核v57, UC 产物,默认同理 UC,国人庞大群体

一二三控件均为直接打开文件选取,无任何操作选择提示

## 某vivo机器

第一个控件出现系统级提示

- 照片和视频
- 所有文件

如图
![image](https://user-images.githubusercontent.com/19513289/53385935-268db700-39bb-11e9-9b52-fcd263f74fbc.png)

打开 照片和视频, 宫格的第一个就是拍照.

## 初步总结

不同设备以及不同浏览器之间行为有差异

> 不同设备 * 不同浏览器 = ∞

案件情况:

按照`actionsheet`预期设置两个`action`

- 拍照
- 选文件

如果`拍照`设置了`capture`属性,会根据预期直接调用相机;

但单击`选文件`可能会弹出**另一个**系统级的`actionsheet`,包含`拍照`和`选文件`两个选项.

可能会导致重复了虚拟的`actionsheet`操作.

但可能部分浏览器或者设备则两个`action`选项都会出现系统级的`actionsheet`或者直接选取文件.

**Comment by levy9527** [comment]
先圈定范围：微信浏览器打开，情况如何
