### ISSUE TITLE
gif无法正常上传

### ISSUE THREAD

**Issue by rexerwang** [FEMessage/upload-to-ali#104]
## Describe the bug
gif无法正常上传，被压缩为png格式。

## Screenshots
![image](https://user-images.githubusercontent.com/15629940/67653098-d2403a00-f982-11e9-9aaa-1be7e5dfc226.png)
![image](https://user-images.githubusercontent.com/15629940/67653126-eedc7200-f982-11e9-954f-d18ca3c45e64.png)
![2019-10-28 13-06-01屏幕截图](https://user-images.githubusercontent.com/15629940/67653414-3d3e4080-f984-11e9-907d-c35dd4e58eec.png)

## Expected behavior
能支持gif原图上传

## environment information
 - Version: v1.9.0
 - OS: Ubuntu
 - Browser: Chrome

**Comment by levy9527** [comment]
收到！
