### ISSUE TITLE
下载文件名称与上次文件名称不一致

### ISSUE THREAD

**Issue by dream2023** [FEMessage/upload-to-ali#140]
如果上传中文文件，会被encodeURIComponent，当下载的时候，就会出现如图所示，测试提了BUG

![file-read-20007](https://user-images.githubusercontent.com/19297757/71706100-dc1c6880-2e1d-11ea-8dfa-ba71dc90bda9.png)
![file-read-20008](https://user-images.githubusercontent.com/19297757/71706103-de7ec280-2e1d-11ea-9706-86bc8e3f5f00.png)

**Comment by levy9527** [comment]
这个，中文名，不这样，会报错呀。

**Comment by dream2023** [comment]
> 这个，中文名，不这样，会报错呀。

https://www.w3school.com.cn/tags/att_a_download.asp 类似a标签是可以指定下载名称的，你可以动态创建一个a标签，赋值属性，自动触发click事件进行下载

**Comment by dream2023** [comment]
> 这个，中文名，不这样，会报错呀。

然后再销毁

**Comment by dream2023** [comment]
```js
const a = document.createElement('a')
a.setAttribute('href', 'https://deepexi.oss-cn-shenzhen.aliyuncs.com/xpaas-console/enterprise_logo_deepexi_white.svg')
a.setAttribute('download', 'test')
a.setAttribute('target', '_blank')
a.click()
```

**Comment by levy9527** [comment]
收到，安排跟进下。

**Comment by lianghx-319** [comment]
了解后发现是，用户自己使用 file-saver 下载文件，捕获了 filename 后没有自行 decodeUriComponent，组件对于 file 的默认行为是执行 window.open，此时浏览器会自动 decode，如果浏览器不支持渲染该文件，则会自动转为下载。
