### ISSUE TITLE
关于 imgpreview 的 bug

### ISSUE THREAD

**Issue by cjfff** [FEMessage/upload-to-ali#23]
**Describe the bug**
在 `el-dialog` 中使用该组件，上传成功后，点击图片预览，这时候摁下键盘 `esc` 键，`el-dialog` 会关闭，但是此时图片的 `preview` 会还在，再次点开会 `el-dialog` 会再出现。

**Screenshots**
![table](https://user-images.githubusercontent.com/20502762/57364269-6c35df80-71b5-11e9-8d1c-96324b4873b8.gif)

**Expected behavior**
`el-dialog` 后图片的 `preview` 能关闭

**environment information: **
 - Version v1.5.0
 - OS: window10
 - Browser chrome

**Comment by 2nthony** [comment]
猜测是`img-preview`记录着图片`url`,点击图片的关闭才会删除内部的`url`值

**Comment by levy9527** [comment]
升级 `@femessage/img-preview` 即可
