### ISSUE TITLE
the bug of default slot

### ISSUE THREAD

**Issue by cjfff** [FEMessage/upload-to-ali#25]
**Describe the bug**
使用场景如果不是 `upload img` 的话，我们有时候也会需要进行一个自定义的样式反馈给用户知道他上传成功了，但是我使用 `default slot` 的时候遇到一个问题，上传成功后会整个组件都消失掉，没有任何的显示内容。详情请看下面的 `gif` 图片。

查看了源码，下面来描述下这个 `bug` 是如何产生的。

使用图
![image](https://user-images.githubusercontent.com/20502762/57705246-13bf8000-7696-11e9-8482-c4e4513161b6.png)

源码图
![image](https://user-images.githubusercontent.com/20502762/57705402-68fb9180-7696-11e9-8d3f-5b0c9baae467.png)

首先这里就是定义的 `default slot`, 我们如果传入了的话，上传成功后，内部的 `canUpload: boolean` 属性就会因为计算属性触发上传上限变为 `false`
![image](https://user-images.githubusercontent.com/20502762/57705326-3782c600-7696-11e9-8142-e9d4e13f04a4.png)

emmmmm 所以 中间 `default slot` 的外层就直接被 `if` 语句干掉了

**Screenshots**
![upload](https://user-images.githubusercontent.com/20502762/57705089-c4794f80-7695-11e9-9856-119a610336dd.gif)

**Expected behavior**
希望对非图片上传做一个比较好的支持

**environment information: **
 - Version v1.5.0
 - OS: windows
 - Browser chrome

**Comment by donaldshen** [comment]
```html
<upload-to-ali  v-model="fileUrl">
  <el-button type="button">选择文件</el-button>
</upload-to-ali>
<a :href="fileUrl" target="__blank">{{ fileUrl }}</a>
```
可以参考这个案例，把上传完的结果放在upload-to-ali以外也是可以的

目前upload-to-ali的slot已经有点混乱了，建议重构而不是增加slot😭

**Comment by cjfff** [comment]
> ```
> <upload-to-ali  v-model="fileUrl">
>   <el-button type="button">选择文件</el-button>
> </upload-to-ali>
> <a :href="fileUrl" target="__blank">{{ fileUrl }}</a>
> ```
> 
> 可以参考这个案例，把上传完的结果放在upload-to-ali以外也是可以的
> 
> 目前upload-to-ali的slot已经有点混乱了，建议重构而不是增加slot😭

好的，谢谢问题解答！
