### ISSUE TITLE
图片或文件上传前希望能提供个接口获取文件信息以判断尺寸等是否符合要求

### ISSUE THREAD

**Issue by neishiliu** [FEMessage/upload-to-ali#41]
现有文档中没有执行上传前的接口，图片或文件上传前希望能提供个接口获取文件信息以判断尺寸等是否符合要求

**Comment by levy9527** [comment]
场景是啥，可以描述一下吗。

**Comment by neishiliu** [comment]
> 场景是啥，可以描述一下吗。

上传商品图片的时候需要判断图片尺寸是否符合要求，以及大小等是否符合要求，需要根据这些结果自定义提示。目前没有上传前的钩子，拿不到图片数据

**Comment by 2nthony** [comment]
🤔意思是不是想自行定制一个对这次上传的文件的提示框.

**Comment by donaldshen** [comment]
可以在upload阶段增加一个钩子函数，传入选中的文件files: FileList，钩子函数返回一个promise，resolve则继续upload流程，reject则取消。
大小要求可以通过file.size判断；
image的尺寸要求，可以先判断file.type，然后createImageBitmap(file)拿到位图的宽高来判断
