### ISSUE TITLE
删除图片时，浏览器控制台报错

### ISSUE THREAD

**Issue by quixote1304629** [FEMessage/upload-to-ali#46]
**Describe the bug**

**Screenshots**
![first-tesee](https://user-images.githubusercontent.com/32378929/60255168-ca538900-9901-11e9-80ba-256cc818e509.gif)
![image](https://user-images.githubusercontent.com/32378929/60255240-f8d16400-9901-11e9-9eca-6895e57441b3.png)
![image](https://user-images.githubusercontent.com/32378929/60255406-51a0fc80-9902-11e9-92dd-5400f5e00d1b.png)

**To Reproduce**
1. 在el-form-render中使用‘upload-to-ali@1.0.7’组件
2. 点击+上传图片
3. 点击删除图片，此时浏览器控制台报红(错误信息如图)
**Expected behavior**
删除图片不报错

**environment information:**
 - Version [1.0.7]
 - Browser [ chrome]

**Comment by levy9527** [comment]
你好，感谢反馈，这周内解决。
